name: Keploy
on: [pull_request,push]
jobs:
  node_linux:
    runs-on: ubuntu-latest
    environment: secrets  # Ensure you specify the environment if it's an environment-level secret
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install curl
      run: sudo apt-get update && sudo apt-get install -y curl
    - name: Print all environment variables for debugging
      run: printenv
    - name: Run the node-express-graphql template
      run: |
        source /home/runner/work/node-express-graphql-template/node-express-graphql-template/.github/workflows/testa_workflow_scripts/keploy.sh
      env:
          GITHUB_TOKEN: ${{ secrets.SECRETS }}